export const exchange_classic_eyeglasses = {
  result: [
    {
      dataType: "TYPE_GRID",
      cols: 2,
      title: "Choose from our Classic Range of Products",
      titlePosition: "center",
      bottomSpace: 8,
      topSpace: 16,
      items: [
        {
          url: "/eyeglasses/brands/vincent-chase-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile1.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "BestSellers",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Best Sellers|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/trending-classic.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile2.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Trending",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Trending|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/promotions/new-arrivals-classic-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile3.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "NewArrival",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|New Arrival|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/vincent-chase-eyeglasses/air-collection.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile4.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "ComfortWear",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Comfort Wear|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/airflex-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile5.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Airflex",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Airflex|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/metal.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile6.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Metal",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Metal|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/vincent-chase-eyeglasses/clip-ons.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile7.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "ClipOn",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Clip On|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/blue-cut.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile8.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "ComputerEyeglasses",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Computer Eyeglasses|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/promotions/vc-jj-halfrim.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile9.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "HalfRim",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Half Rim|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/promotions/vc-jj-rimless.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile10.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "RimLess",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|RimLess|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/frame-shape/rectangle.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile11.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Rectangle",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Rectangle|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/vincent-chase-eyeglasses/wayfarer.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile12.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Wayfarer",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Wayfarer|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/marketing/vincent-chase-air-silicon.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile13.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "AirSilicon",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Air Silicon|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/hd-acetate.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile14.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "HDAcetate",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|HD Acetate|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/marketing/new-vc-collection-vaga-royale.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile15.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "VagaRoyale",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Vaga Royale|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/reading-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile16.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "ReadingGlasses",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Reading Glasses|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/vincent-chase-eyeglasses/aviator.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile17.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Aviator",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Aviator|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/vincent-chase-eyeglasses/air-collection.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile18.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Sports",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Sports|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/vincent-chase-eyeglasses/vc-round-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile19.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Round",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Round|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/frame-shape/cat-s-eye.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/ClassicEyeTile20.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "CatEye",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Cat Eye|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
      ],
    },
    {
      dataType: "TYPE_GRID",
      cols: 2,
      title: "Choose from our Premium Range of Products",
      titlePosition: "center",
      bottomSpace: 8,
      topSpace: 16,
      items: [
        {
          url: "/eyeglasses/brands/john-jacobs-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile1.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "JohnJacobs",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|John Jacobs|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/ray-ban-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile2.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "RayBan",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Ray Ban|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/marketing/bestsellers-premium-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile3.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "BestSellers",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Best Sellers|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/promotions/new-arrivals.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile4.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "New Arrivals",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|NewArrivals|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/trending-jj-new.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile5.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Trending",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Trending|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/promotions/jj-metal-collection.htmll",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile6.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Metal",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Metal|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/premium-half-rim.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile7.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "HalfRim",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Half Rim|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/premium-eyeglasses/rimless.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile8.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Rimless",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Rimless|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/premium-eyeglasses/round.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile9.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Round",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Round|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/premium-eyeglasses/wayfarer.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile10.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Wayfarer",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Wayfarer|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/premium-eyeglasses/aviator.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile11.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Aviator",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Aviator|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/premium-eyeglasses/rectangle.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile12.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Rectangle",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|WayRectanglefarer|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/collections/premium-eyeglasses/cat-eye.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile13.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "CatEye",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Cat Eye|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/ray-ban-eyeglasses.htm",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile2.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "RayBan",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Ray Ban|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/oakley-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile14.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Oakley",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Oakley|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/carrera-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile15.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Carrera",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Carrera|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/tommy-hilfiger.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile16.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "TommyHilfiger",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Tommy Hilfiger|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
        {
          url: "/eyeglasses/brands/vogue-eyeglasses.html",
          img: "https://static1.lenskart.com/media/mobile/universal/images/returnExchange/PremiumEyeTile17.jpg",
          page: "ExchangeClassicEyeglasses:grid",
          componentName: "Vogue",
          dtmObj: {
            linkPageName: "web|Exchange Classic Eyeglasses",
            linkName: "web|Vogue|grid",
            icid: true,
            event: "generic-int-link",
          },
        },
      ],
    },
  ],
};
